.buildkite/pipeline.yml
.github/workflows/build.yml
.github/workflows/tag.yml
.gitmodules
README.md
WORKSPACE

Not functional yet, @ludgerpaehler if you have cycles to try to fix.

Use workspace clone

---

.github/workflows/python_format.yml
src/enzyme_ad/jax/primitives.py
test/bench_vs_xla.py
test/lit_tests/ir.pyt
test/lit_tests/lit.cfg.py
test/llama.py
test/test.py

This is the same formatter as LLVM is using.

Python format

---

WORKSPACE
src/enzyme_ad/jax/compile_with_xla.cc
src/enzyme_ad/jax/compile_with_xla.h
src/enzyme_ad/jax/enzyme_call.cc
src/enzyme_ad/jax/primitives.py

Requires corresponding XLA changes.
Also requires later changes to XLA to force compilation of all functions, not just the outermost one.

Add support for use of xla runtime

---

WORKSPACE
src/enzyme_ad/jax/BUILD
src/enzyme_ad/jax/Implementations/HLODerivatives.td
src/enzyme_ad/jax/Implementations/MHLODerivatives.td
src/enzyme_ad/jax/Implementations/StableHLOAutoDiffOpInterfaceImpl.cpp
src/enzyme_ad/jax/Implementations/StableHLODerivatives.td
src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/Passes/Passes.h
src/enzyme_ad/jax/Passes/Passes.td
src/enzyme_ad/jax/primitives.py
test/bench_vs_xla.py

Note to self, need to finish adding the out_idx_map everywhere to handle jax's dead arg elim
Edit: done

Jax reverse more

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
test/lit_tests/paddotgeneral.mlir
test/lit_tests/padmultiply.mlir

simply mul-of-pad

---

BUILD
src/enzyme_ad/jax/BUILD
src/enzyme_ad/jax/compile_with_xla.cc

Fix `complex` dialect registration

---

src/enzyme_ad/jax/Implementations/HLODerivatives.td

See https://github.com/EnzymeAD/Reactant.jl/issues/57.

Mark stablehlo.compare as inactive

---

BUILD
src/enzyme_ad/jax/Implementations/HLODerivatives.td
src/enzyme_ad/jax/Passes/ArithRaising.cpp
src/enzyme_ad/jax/enzymexlamlir-opt.cpp
test/BUILD
test/lit.site.cfg.py.in
test/lit_tests/diffrules/chlo/conj.mlir
test/lit_tests/diffrules/stablehlo/clamp.mlir
test/lit_tests/diffrules/stablehlo/complex.mlir
test/lit_tests/diffrules/stablehlo/dot_general.mlir
test/lit_tests/diffrules/stablehlo/einsum.mlir
test/lit_tests/diffrules/stablehlo/fft.mlir
test/lit_tests/diffrules/stablehlo/imag.mlir
test/lit_tests/diffrules/stablehlo/multiply.mlir
test/lit_tests/diffrules/stablehlo/real.mlir

Implement clamp derivatives as a pretext to enable numerical tests via the stablehlo interpreter.

Clamp derivatives

---

src/enzyme_ad/jax/__init__.py
src/enzyme_ad/jax/primitives.py
test/BUILD
test/test_utils.py
test/testffi.py

Nicer hlo ffi

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
src/enzyme_ad/jax/primitives.py
test/lit_tests/dynamic_update_slice.mlir

Constant propagation for dynamic update slice

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
test/lit_tests/powint.mlir

fix: handle integers for stablehlo.power

---

.gitignore
BUILD
README.md
WORKSPACE

Adds support for LSP

---

src/enzyme_ad/jax/Passes/ArithRaising.cpp
src/enzyme_ad/jax/Passes/Passes.td
test/lit_tests/broadcastdiff.mlir

Corresponding Enzyme PR for batched autodiff: https://github.com/EnzymeAD/Enzyme/pull/2181
Is `arith-raise` the correct place for this or does this need a new pass?

`enzyme.broadcast` conversion

---

src/enzyme_ad/jax/Passes/LibDeviceFuncsRaisingPass.cpp
src/enzyme_ad/jax/Passes/Passes.h
src/enzyme_ad/jax/Passes/Passes.td
test/lit_tests/libdevice_raise.mlir

add pass for raising libdevice calls to ops

---

src/enzyme_ad/jax/Implementations/StableHLOAutoDiffOpInterfaceImpl.cpp
test/lit_tests/diffrules/stablehlo/if_remove.mlir

Partial unblocking fix for https://github.com/EnzymeAD/Enzyme-JAX/issues/230

Fix removal of if op

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
src/enzyme_ad/jax/primitives.py
test/lit_tests/chlo_is_inf_const_prop.mlir

Added const prop for chlo.is_inf

---

src/enzyme_ad/jax/Implementations/StableHLOAutoDiffOpInterfaceImpl.cpp
src/enzyme_ad/jax/Passes/ArithRaising.cpp
src/enzyme_ad/jax/Passes/LowerKernel.cpp
test/lit_tests/diffrules/stablehlo/if.mlir

@Pangoraw I realized we were getting nondeterminstic results for the if op interface, so I changed it to a mapvector

Fixup tests

---

src/enzyme_ad/jax/Passes/LibDeviceFuncsRaisingPass.cpp
test/lit_tests/libdevice_raise.mlir

Raise powi and absi to the math dialect

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
test/lit_tests/addsumsimplify.mlir

Apply `NoNanAddSubSimplify` pattern to integer unconditionally

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
test/lit_tests/issue_264.mlir

Support f8E4M3FN in `fromTensor`

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
src/enzyme_ad/jax/primitives.py
test/lit_tests/whiledeadarg.mlir

Reland: pattern to remove dead results of stablehlo.while

---

src/enzyme_ad/jax/Passes/LibDeviceFuncsRaisingPass.cpp
test/lit_tests/arith_raise.mlir

add compare and constant

---

src/enzyme_ad/jax/Passes/LLVMToControlFlow.cpp
src/enzyme_ad/jax/Passes/Passes.h
src/enzyme_ad/jax/Passes/Passes.td
src/enzyme_ad/jax/enzymexlamlir-opt.cpp
test/lit_tests/raising/llvm_to_cf.mlir

This is extracted from https://github.com/EnzymeAD/Enzyme-JAX/pull/265 to ease code review, with added unit tests

Add LLVM to CF raising pass

---

src/enzyme_ad/jax/Passes/ControlFlowToSCF.cpp
src/enzyme_ad/jax/Passes/Passes.td
src/enzyme_ad/jax/enzymexlamlir-opt.cpp
test/lit_tests/raising/cf_to_scf.mlir

This pass works on region in general (thus llvm.func), while the upstream pass only works on FuncOp

Add custom CF to SCF raising pass

---

src/enzyme_ad/jax/BUILD
src/enzyme_ad/jax/RegistryUtils.cpp
src/enzyme_ad/jax/TransformOps/RaisingTransformOps.cpp
src/enzyme_ad/jax/TransformOps/RaisingTransformOps.h
src/enzyme_ad/jax/TransformOps/RaisingTransformOps.td
src/enzyme_ad/tools/enzymexlamlir-tblgen.cpp
test/lit_tests/patterns/remove_ivs.mlir

Extracted from #265. Fixed a bug and added test

Add RemoveIV pattern

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp

@gleasonk temporarily vendoring your code from https://github.com/openxla/stablehlo/pull/2709 per two people ironically having hit an issue on complex solved by it in the past day.
Will replace things to call stablehlo proper once merged and integrated

Fix complex import from stablehlo

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
src/enzyme_ad/jax/primitives.py
test/lit_tests/if_pred_propagation.mlir

All uses of a if predicate which are either in the true or false branch can be replaced with the true or false value accordingly.

If predicate value propagation

---

src/enzyme_ad/jax/Implementations/StableHLOAutoDiffOpInterfaceImpl.cpp
src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
src/enzyme_ad/jax/primitives.py
test/lit_tests/diffrules/stablehlo/reduce_window.mlir

implement reduce_window reverse when reduction is add

---

.github/workflows/build.yml
.github/workflows/format.yml
.github/workflows/python_format.yml

Ref https://github.com/EnzymeAD/Enzyme-JAX/pull/347#pullrequestreview-2619506969.

[CI] Run `format` job only on C/C++ files and exclude external packages

---

.clang-format-ignore
.github/workflows/format.yml

Ref: https://github.com/EnzymeAD/Enzyme-JAX/pull/378#issuecomment-2680927087.

Make clang-format ignore `src/external`

---

src/enzyme_ad/jax/Passes/AffineToStableHLORaising.cpp
test/lit_tests/raising/affine_to_stablehlo6.mlir
test/lit_tests/raising/affine_to_stablehlo7.mlir

No more transposes, broadcast_in_dim instead

StableHLORaising: Generalize alignment from differently loaded tensors

---

src/enzyme_ad/jax/Passes/AffineToStableHLORaising.cpp

(similar to affine.if raising)

raise scf.if

---

src/enzyme_ad/jax/Passes/AffineToStableHLORaising.cpp
test/lit_tests/raising/affine_to_stablehlo15.mlir

Using scatter/gather for loads since the indices are now dynamic.

Raise affine.for to stablehlo.while

---

src/enzyme_ad/jax/Passes/AffineToStableHLORaising.cpp
src/enzyme_ad/jax/Passes/ArithRaising.cpp
test/lit_tests/raising/affine_to_stablehlo13.mlir
test/lit_tests/raising/affine_to_stablehlo16.mlir

apply: use stablehlo variant of expandEmitExpr + more complex loads

---

src/enzyme_ad/jax/Passes/AffineCFG.cpp
test/lit_tests/raising/affineaarchorder.mlir

Fixaarch64

---

src/enzyme_ad/jax/Passes/CanonicalizeFor.cpp
test/lit_tests/canonicalizefor/doWhile.mlir

Closes #508. cc @arpitj1, I would appreciate your review.

Handle ne neg step with cmp taking the iv

---

src/enzyme_ad/jax/Passes/AffineCFG.cpp
src/enzyme_ad/jax/Passes/CanonicalizeFor.cpp
test/lit_tests/canonicalizefor/ifYieldCanonicalize2.mlir

reduction for pass

---

src/enzyme_ad/jax/Passes/AffineCFG.cpp
src/enzyme_ad/jax/Passes/AffineUtils.h
src/enzyme_ad/jax/Passes/SimplifyAffineExprs.cpp
test/lit_tests/raising/affinecfg6.mlir

Add patterns for affine expr simplification into AffineCFG

---

src/enzyme_ad/jax/Passes/AffineCFG.cpp

- improve the `definedOutside` check to properly handle block arguments;
- use the rewriter to create blocks, bad and extremely-hard-to-debug things may happen otherwise.

fixes post #542

---

src/enzyme_ad/jax/Passes/AffineCFG.cpp
src/enzyme_ad/jax/Passes/AffineToStableHLORaising.cpp
src/enzyme_ad/jax/Passes/Passes.td
test/lit_tests/raising/affine_to_stablehlo15.mlir
test/lit_tests/raising/affine_to_stablehlo16.mlir
test/lit_tests/raising/affine_to_stablehlo_forred.mlir
test/lit_tests/raising/affine_to_stablehlo_lockstep_for.mlir
test/lit_tests/raising/affine_to_stablehlo_reduction.mlir
test/lit_tests/raising/raise-affine-to-stablehlo-affine-for-iter-args3.mlir
test/lit_tests/raising/raise-affine-to-stablehlo-affine-for-iter-args4.mlir
test/lit_tests/raising/raise-affine-to-stablehlo-affine-for-iter-args5.mlir

We don't actually have any loops with this pattern currently

Lockstep for op raising

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
test/lit_tests/dusreshape.mlir

Works only when the reshape inserts/remove new unary dimensions (ie. squeeze/unsqueeze).
ref https://github.com/EnzymeAD/Enzyme-JAX/issues/575

Reshape(DynamicUpdateSlice) -> DynamicUpdateSlice(Reshape, Reshape)

---

src/enzyme_ad/jax/Passes/AffineToStableHLORaising.cpp
test/lit_tests/raising/affine_to_stablehlo_pforred2.mlir

fixes https://github.com/EnzymeAD/Enzyme-JAX/issues/579

Add fix for parallel reduction dimension crash

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
test/lit_tests/broadcastisreshape2.mlir

Fix broadcast is reshape

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
test/lit_tests/dus_to_i32.mlir

let me know if it should trigger with a particular passses value in enzyme-hlo-opt

Add opt to convert const dus to i32 indices

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
test/lit_tests/padconcat_to_concatpad.mlir

PadConcat to (MaybePad)ConcatPad

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
test/lit_tests/sliceselecttoselectslice.mlir

Slice(Select) to Select(Slice)

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp

Check single use in padconcat ->concatpad

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
test/lit_tests/mul_reordering.mlir
test/lit_tests/while_pad_induction_reduction.mlir

simplified the yield to be without padded values
https://github.com/EnzymeAD/Enzyme-JAX/issues/632

while with pad in yield 

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
test/lit_tests/transposeselect.mlir

feat: transpose select

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
test/lit_tests/dus_slice_simplify.mlir

The new dus start indice should be 0 if dusStart < ignored since we clamp at ignored.
Otherwise it should be the difference between dusStart and ignored.
Also added an assert that since dus will happily run with OOB

Fix dusStartIndices in dus slice simplify

---

test/lit_tests/concat_concat_to_dus.mlir
test/lit_tests/dus_to_concat.mlir
test/lit_tests/group_comms.mlir
test/lit_tests/lower_extend.mlir
test/lit_tests/lower_rotate.mlir
test/lit_tests/lower_wrap.mlir
test/lit_tests/mul_reordering.mlir
test/lit_tests/recognize_extend.mlir
test/lit_tests/recognize_rotate.mlir
test/lit_tests/recognize_wrap.mlir
test/lit_tests/recognize_wrap2.mlir
test/lit_tests/while_induction_reduction.mlir
test/lit_tests/while_induction_reduction2.mlir
test/lit_tests/whiledus.mlir
test/lit_tests/whiledus2.mlir

@wsmoses Couldn't immediately figure out `test/lit_tests/while_induction_reduction.mlir` so I XFAIL'd it for now. Should we merge and get back to it later?

Test fixes

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
test/lit_tests/sliceextend.mlir

I noticed I made a mistake in the operand order and the test I'd added because it used the same values for `dim` and `lhs`. ~~This is a quick fix, I'll add a better test with my incoming wrap(slice) pr.~~ I'm looking to add a better test here

Fix ExtendOp construction

---

test/lit_tests/communication/rotate.mlir

The opt pattern does not match because of:
https://github.com/EnzymeAD/Enzyme-JAX/blob/21e0b857aa26219b0c439e39c80b4b4df59b4706/src/enzyme_ad/jax/Passes/OptimizeCommunication.cpp#L1113-L1115

Fix rotate test

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
test/lit_tests/transposeextend.mlir
test/lit_tests/transposerotate.mlir
test/lit_tests/transposewrap.mlir

`transpose([extend/wrap/rotate]) -> [extend/wrap/rotate](transpose)`

TransposeWrap, TransposeExtend, TransposeRotate

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
test/lit_tests/extendelementwise.mlir
test/lit_tests/extendsplat.mlir
test/lit_tests/wrapelementwise.mlir

Extend of Elementwise and Extend of splat and Wrap of elementwise

---

src/enzyme_ad/jax/Implementations/HLODerivatives.td
test/lit_tests/diffrules/stablehlo/convolution_transpose.mlir

conv: Handle lhs dilation correctly

---

src/enzyme_ad/jax/Implementations/StableHLOAutoDiffOpInterfaceImpl.cpp

mincut: fix incomplete reverse graph

---

src/enzyme_ad/jax/Implementations/StableHLOAutoDiffOpInterfaceImpl.cpp

@ftynse in post commit review, know of a better place for this comparator (or is there one in the wild)

Fix sort to be a valid partial order

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
test/lit_tests/transpose_if2.mlir

fix: some fixes for if ops lift common ops

---

src/enzyme_ad/jax/Implementations/StableHLOAutoDiffOpInterfaceImpl.cpp
test/lit_tests/diffrules/stablehlo/while.mlir
test/lit_tests/diffrules/stablehlo/while2.mlir
test/lit_tests/diffrules/stablehlo/while3.mlir
test/lit_tests/diffrules/stablehlo/while_checkpointing.mlir
test/lit_tests/diffrules/stablehlo/while_mincut.mlir

@Pangoraw @pengmai another one

[Enzyme][While] Fix multi ind usage

---

src/enzyme_ad/jax/Passes/ConvertParallelToGPU.cpp
src/enzyme_ad/jax/Passes/ConvertPolygeistToLLVM.cpp
src/enzyme_ad/jax/Passes/ParallelSerialization.cpp

@ivanradanov so this is needed if we can't tell the bound sizes of the loop [e.g. hidden behind fn call for dim3]

GPU: emit noop alternative, if available

---

test/lit_tests/canonicalizefor/remove_iv_related.mlir

Fixes https://github.com/EnzymeAD/Enzyme-JAX/issues/1161

More tests to RemoveIVRelated pattern

---

src/enzyme_ad/jax/Passes/ConvertPolygeistToLLVM.cpp
src/enzyme_ad/jax/Passes/LLVMToAffineAccess.cpp
test/lit_tests/gpualloc_deadstore_nonasync.mlir
test/lit_tests/raising/convert_polygeist_to_multiblockerr.mlir

* fix swapped threadIdx.x/y in kernel launch
* fix SimplyDeadAlloc being too aggressive with enzymexla.memcpy

GPU lowering fixes

---

.github/workflows/build.yml
src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
src/enzyme_ad/jax/primitives.py
test/lit_tests/add_rotate.mlir
test/lit_tests/subtract_rotate.mlir

feat: rewrite subtract/add (with optional multiply) rotate as reduce window

---

src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
test/lit_tests/conv_padding.mlir

feat: absorb spatial padding into conv

---

.github/workflows/test-gb-25.yml

With frequent rebases of the branch, using commit hashes is a minefield.

[CI] Use again `Reactant#main` for GB-25 test

---

src/enzyme_ad/jax/Passes/ConvertParallelToGPU.cpp

We are using intrinsics that require these.

bump minimum required default gpu versions

---

src/enzyme_ad/jax/raise.cpp

Requires changes to libRaise.so plugin

allow for target library linkage via flags

---

test/jaxmd.py

Increase tolerance for jaxmd test

---

.github/workflows/test-gb-25.yml

Ref https://github.com/EnzymeAD/Enzyme-JAX/pull/1375#issuecomment-3263844031.

[CI] Temporary pin CUDA.jl in GB-25 test

---

.github/workflows/build.yml

Updated permissions for the build workflow to allow writing contents and statuses.

ci: fix permissions part 2

---

.github/workflows/build.yml
src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
src/enzyme_ad/jax/TransformOps/TransformOps.td
src/enzyme_ad/jax/primitives.py
test/lit_tests/case_to_if.mlir

mostly because we have a bunch of if op optimizations written, but not any for case

feat: rewrite case to if
