EnzymeAD/Enzyme-JAX

- README.md
When building the project, the following error appeared:
```
Error in fail: Current Bazel version is 5.3.0; expected at least 5.4.0
```
Update the documentation to indicate the correct version.
> Update docs for Bazel requirements

- BUILD
- test/bench_vs_xla.py
- test/llama.py
- test/test.py
JAX already depends on absltest so we have it "for free" as a
dependency. Using a test framework composes better with build
infrastructure.
> use absltest for tests

- src/enzyme_ad/jax/enzyme_call.cc
- src/enzyme_ad/jax/primitives.py
- test/bench_vs_xla.py
The missing ')' was causing a bug on the old pipeline, which was not
caught by the current tests. This fixes the issue and adds tests to
prevent a regression.
> Add missing ')' to enzyme_call and add tests for old pipeline

- src/enzyme_ad/jax/primitives.py
Fixes a reference count issue  during a timeit call where we tried to erroneously delete out_shapes.
> Make enzyme_ref delete in_shapes instead of out_shapes

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- test/lit_tests/reshapeslice.mlir
Currently only works for reshapes obviously splitting dimensions.
> slice(reshape) -> reshape(slice)

- src/enzyme_ad/jax/Implementations/HLODerivatives.td
- test/lit_tests/einsum.mlir
- test/lit_tests/einsumcomplex.mlir
- test/lit_tests/unaryeinsum.mlir
Fixes #82 
@wsmoses I don't know much about LLVM, so I don't know how to implement them. But I wrote the prototypes and some annotations on how to continue the implementation.
> Add `stablehlo.einsum`, `stablehlo.unary_einsum` diffrules

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- src/enzyme_ad/jax/TransformOps/TransformOps.td
- test/lit_tests/convolutiontranpose.mlir
I wrote the optimization we discussed about but for stablehlo.convolution.
```mlir
%0 = stablehlo.transpose %arg0, dims = [3, 2, 1, 0] : (tensor<5x3x224x224xf32>) -> tensor<224x224x3x5xf32>
%1 = stablehlo.transpose %arg1, dims = [3, 2, 1, 0] : (tensor<2x3x10x10xf32>) -> tensor<10x10x3x2xf32>
%2 = stablehlo.convolution(%0, %1) dim_numbers = [0, 1, f, b]x[0, 1, i, o]->[0, 1, f, b], window = {stride = [1, 1], lhs_dilate = [1, 1], rhs_dilate = [1, 1]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64} : (tensor<224x224x3x5xf32>, tensor<10x10x3x2xf32>) -> tensor<215x215x2x5xf32>
```
to
```mlir
%0 = stablehlo.convolution(%arg0, %arg1) dim_numbers = [b, f, 1, 0]x[o, i, 1, 0]->[0, 1, f, b], window = {stride = [1, 1], lhs_dilate = [1, 1], rhs_dilate = [1, 1]} {batch_group_count = 1 : …
```
> optimize convolution of transpose

- src/enzyme_ad/jax/Implementations/StableHLOAutoDiffOpInterfaceImpl.cpp
- src/enzyme_ad/jax/Implementations/WhileLoopInfo.cpp
- src/enzyme_ad/jax/Implementations/WhileLoopInfo.h
- src/enzyme_ad/jax/Passes/EnzymeHLOUnroll.cpp
- test/lit_tests/diffrules/stablehlo/while.mlir
- test/lit_tests/diffrules/stablehlo/while2.mlir
- test/lit_tests/diffrules/stablehlo/while3.mlir
> WhileOp reverse derivative

- src/enzyme_ad/jax/TransformOps/GenerateApplyPatterns.cpp
- test/lit_tests/generate_td.mlir
To clean up `Reactant.@code_hlo` output
> remove transform.with_named_sequence attribute

- WORKSPACE
- third_party/enzyme/workspace.bzl
- third_party/hedron_compile_commands/workspace.bzl
- third_party/jax/workspace.bzl
- third_party/xla/workspace.bzl
- workspace.bzl
Following EnzymeAD/Reactant.jl#421, I'm moving build deps to different files inside the `third_party` folder.
I would prefer to also pack the calls in `WORKSPACE` because it's similar in ReactantExtra, but we can do that later.
> Modularize Bazel build

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- src/enzyme_ad/jax/TransformOps/TransformOps.td
- src/enzyme_ad/jax/primitives.py
- test/lit_tests/addnegate.mlir
- test/lit_tests/addsumsimplify.mlir
- test/lit_tests/binarytranspose.mlir
- test/lit_tests/selfsubtract.mlir
> feat: common simplifications

- src/enzyme_ad/jax/BUILD
- src/enzyme_ad/jax/Passes/ConsumingInterpreterPass.cpp
- src/enzyme_ad/jax/Passes/Passes.h
- src/enzyme_ad/jax/Passes/Passes.td
- src/enzyme_ad/jax/TransformOps/GenerateApplyPatterns.cpp
- test/lit_tests/transform_in_function.mlir
- Modify the TD generation pass to emit the transform module if requested by a flag.
- Introduce a separate interpreter pass that moves the transform script into a separate module to allow it to be applied to the pass anchor operation, and then remove it entirely.
> Transform interpreter runnable from within a function

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- src/enzyme_ad/jax/TransformOps/TransformOps.td
- src/enzyme_ad/jax/primitives.py
- test/lit_tests/diffrules/stablehlo/if_remove.mlir
- test/lit_tests/select_if.mlir
If a select has uses within a if with the same predicate, the uses can be replaced with either the true or false value.
In a follow-up, we can do the following:
if a select is itself within a if with the same predicate, its result can be replaced with the corresponding operand:
```mlir
%1 = stablehlo.if %pred ({
%0 = stablehlo.select %pred, %a, %b
stablehlo.return %0
}, {
stablehlo.return %other
})
// Transform to
%1 = stablehlo.if %pred ({
stablehlo.return %a
}, {
stablehlo.return %other
})
```
> Add opt to simplify select uses within if

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- src/enzyme_ad/jax/TransformOps/TransformOps.td
- src/enzyme_ad/jax/primitives.py
- test/lit_tests/log_const_prop.mlir
> const prop for log and logp1

- src/enzyme_ad/jax/Implementations/StableHLOAutoDiffOpInterfaceImpl.cpp
- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- src/enzyme_ad/jax/TransformOps/TransformOps.td
- src/enzyme_ad/jax/primitives.py
- test/lit_tests/while_simplify.mlir
@wsmoses you mentioned at some point that unlike scf.for, stablehlo.while cannot reference values which are not passed as arguments. Should I update this optimization to only apply to stablehlo.constant ?
> While simplify opt

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
@mofeing re https://github.com/EnzymeAD/Enzyme-JAX/issues/270 got it in gdb
So basically we were simplifying an add of tensor complex, but that only supported float and otherwise assumed int (which is wrong here since it was complex).
```
(lldb) p op.dump()
%6 = stablehlo.add %cst, %cst_2 : tensor<2x2xcomplex<f64>>
(lldb) p op.getOperand(0)
(mlir::Value) {
impl = 0x0000600000a23de0
}
(lldb) p op.getOperand(0).dump()
%cst = stablehlo.constant dense<(0.000000e+00,0.000000e+00)> : tensor<2x2xcomplex<f64>>
(lldb) p op.getOperand(1).dump()
%cst_2 = stablehlo.constant dense<(1.000000e+00,0.000000e+00)> : tensor<2x2xcomplex<f64>>
```
For now this PR should stop it from failing, but clearly this should be updated to also constprop complex values
> fix cmplx stop

- src/enzyme_ad/jax/Dialect/EnzymeXLAOps.td
- src/enzyme_ad/jax/Passes/Passes.h
- src/enzyme_ad/jax/Passes/Passes.td
- src/enzyme_ad/jax/Passes/PropagateConstantBound.cpp
- test/lit_tests/propagate-constant-values.mlir
Since thread and block IDs are constants, we can propagate these constants in the kernel using the LLVM Range attribute.  When running this pass before the SROA, I saw a reduction in operation counts for `exported_oc.mlir` (from 43131 to 39151), which looks related to bound computations.
> Propagate constant for thread/block index in kernels

- src/enzyme_ad/jax/Passes/ControlFlowToSCF.cpp
bazel-out/darwin_arm64-dbg/bin/src/enzyme_ad/jax/Passes/Passes.h.inc:589:21: error: use of undeclared identifier 'ub'
> fix compilation

- src/enzyme_ad/jax/TransformOps/RaisingTransformOps.cpp
- src/enzyme_ad/jax/TransformOps/RaisingTransformOps.td
- test/lit_tests/patterns/normalize_loop.mlir
Extracted from https://github.com/EnzymeAD/Enzyme-JAX/pull/265. Added test
> Add NormalizeLoop pattern

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- src/enzyme_ad/jax/TransformOps/TransformOps.td
- src/enzyme_ad/jax/primitives.py
- test/lit_tests/binop_const.mlir
> Group constants for commutative ops

- src/enzyme_ad/jax/BUILD
I'd like access to this target to use Enzyme in my project. Is that OK?
> make XLADerivatives target public

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- src/enzyme_ad/jax/TransformOps/TransformOps.td
- src/enzyme_ad/jax/primitives.py
- test/lit_tests/if_remove_unused.mlir
If a result of an if is unused, remove it from the results. This will remove uses in the respective terminators and enable further optimizations.
> Remove unused results from if

- src/enzyme_ad/jax/Implementations/CHLODerivatives.td
- src/enzyme_ad/jax/Implementations/HLODerivatives.td
- src/enzyme_ad/jax/Implementations/MHLOAutoDiffOpInterfaceImpl.cpp
- src/enzyme_ad/jax/Implementations/MHLODerivatives.td
- src/enzyme_ad/jax/Implementations/StableHLOAutoDiffOpInterfaceImpl.cpp
- src/enzyme_ad/jax/Implementations/StableHLODerivatives.td
- src/enzyme_ad/jax/Implementations/XLADerivatives.h
- test/lit_tests/diffrules/stablehlo/gather.mlir
- workspace.bzl
ScatterOp has multiple results, so we need to get the first result (not sure how)
```
bazel-out/k8-dbg/bin/src/enzyme_ad/jax/Implementations/MHLODerivatives.inc:1057:31: error: conversion from 'mlir::mhlo::ScatterOp' to non-scalar type 'mlir::Value' requested 
```
> feat: derivative rule for gather op

- src/enzyme_ad/jax/Passes/ConvertPolygeistToLLVM.cpp
- test/lit_tests/convert-polygeist-to-llvm.mlir
The CallOp lowering pattern was incorrectly passing all operands as a single array to LLVM::CallOp. This caused issues with operand segment sizes since LLVM::CallOp expects the callee and arguments to be passed separately.
This change eliminates the need for manual operand segment size handling since the operation definition now correctly structures the operands.
Fix: #350
> Use the right builder for CallOp

- src/enzyme_ad/jax/primitives.py
The jax.lib.xla_client submodule has been deprecated, and I'm working on cleaning up users of these APIs. In this case, the `register_custom_call_target` can be directly replaced by [`jax.ffi.register_ffi_target`](https://docs.jax.dev/en/latest/_autosummary/jax.ffi.register_ffi_target.html) with `api_version=0`.
In the long run, AFAIK the XLA team are planning on removing support for the legacy custom call API version, so it would be good to eventually migrate the kernels themselves, but I'll leave that for future work.
> Use jax.ffi.register_ffi_target instead of deprecated version in jax.lib.xla_client

- src/enzyme_ad/jax/BUILD
This seems to solve for me locally the error
```
[05:01:02] external/enzyme_ad/src/enzyme_ad/jax/Passes/AffineToStableHLORaising.cpp:19:10: error: module @enzyme_ad//src/enzyme_ad/jax:XLADerivatives does not depend on a module exporting 'mlir/Dialect/Affine/LoopUtils.h'
[05:01:02]    19 | #include "mlir/Dialect/Affine/LoopUtils.h"
[05:01:02]       |          ^
[05:01:02] 1 error generated.
```
As far as I understand, this is defined in https://github.com/llvm/llvm-project/blob/4e44bd027bf4e490380be770172994561616bd2d/utils/bazel/llvm-project-overlay/mlir/BUILD.bazel#L4210-L4239.
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/10587#issuecomment-2676019451
> Add missing dependency to `src/enzyme_ad/jax:XLADerivatives`

- src/enzyme_ad/jax/Passes/CanonicalizeLoops.cpp
- test/lit_tests/if-with-empyty-then.mlir
- test/lit_tests/if_to_select.mlir
- test/lit_tests/switch_to_if.mlir
This PR simplifies IF conditions in two cases: 1) The then branch is empty, and the else is not. In this case, we negate the condition and delete the other branch. 2) The if is flattened to select if both regions contain only pure operations. This allows us to remove problematic if mentioned in this conversation: https://github.com/PRONTOLab/GB-25/issues/11#issuecomment-2670386656
> Simplify If

- .github/workflows/build.yml
Follow up to #378, I missed some `**`s and now CI isn't running in #382, oops!
> [CI] Fix paths triggers for `build` workflow

- src/enzyme_ad/jax/BUILD
- test/lit_tests/BUILD
Addresses https://github.com/EnzymeAD/Enzyme-JAX/pull/394#issuecomment-2684003696.
Opening as draft because I'm not 100% sure this is enough for making tests pass on macOS, but at least on hydra all errors about undefined symbols are gone.
> Add missing deps needed for running the tests

- .github/workflows/build.yml
> CI: Run lit tests on linux

- src/enzyme_ad/jax/Passes/AffineToStableHLORaising.cpp
The [] operator returns a reference and using it to assign to the same densemap can result in invalid memory access if a reallocation of the map happens.
```diff
-      maps[whileRes] = maps[mapping.lookup(forIterArg)];
+      maps[whileRes] = maps.lookup(mapping.lookup(forIterArg));
```
Fix #504, fix https://github.com/PRONTOLab/GB-25/issues/67.
> Do not use subscript to assign to the same densemap

- src/enzyme_ad/jax/Passes/LibDeviceFuncsRaisingPass.cpp
- test/lit_tests/raising/libdevice_raise.mlir
This handles both the NVVM intrinsic calls, which require integer truncation as they all return i32 as opposed to math ops that return the same type as the operand, and the LLVM intrinsic operations.
> raise bit counting ops from nvvm and llvm

- src/enzyme_ad/jax/Passes/CanonicalizeFor.cpp
- test/lit_tests/canonicalizefor/doWhile.mlir
the second added test in #509 was wrong since the range is inclusive in this case. The same logic should be applied for other comp predicates.
> Fix another off by 1

- src/enzyme_ad/jax/Passes/AffineCFG.cpp
- test/lit_tests/raising/merge-inductions-illegal.mlir
Do not stop collecting illegal ops because we may check if the partially collected ones were legal and conclude the legality of the IV.
> MergeInductions fix

- src/enzyme_ad/jax/Passes/AffineCFG.cpp
- test/lit_tests/raising/affinecfg6.mlir
- test/lit_tests/raising/liftintoif.mlir
When a load depends on the conditional value produced by an `scf.if`, lift that load into both conditional branches when possible (no interferring side-effecting operations). This may allow us to turn such loads into affine loads and further raise them.
Additional patterns are needed to fold arithmetic operations into affine forms and further use those to construct and affine load.
> lift memref.load depending on scf.if into that

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- src/enzyme_ad/jax/TransformOps/TransformOps.td
- src/enzyme_ad/jax/primitives.py
- test/lit_tests/iotaconstbroadcast.mlir
This rewrite pattern searches for constant-stride single-dimensional arrays that are broadcasted to higher dimensions, and condenses them into iota operations.
The following input:
```
module{
func.func @test() -> tensor<20x180xi64 >{
%c_1173 = stablehlo.constant dense<[0, 20176, 40352, 60528, 80704, 100880, 121056, 141232, 161408, 181584, 201760, 221936, 242112, 262288, 282464, 302640, 322816, 342992, 363168, 383344]> : tensor<20xi64>
%423 = stablehlo.broadcast_in_dim %c_1173, dims = [0] : (tensor<20xi64>) -> tensor<20x180xi64>
return %423 : tensor<20x180xi64>
}
}
```
Will be transformed into:
```
module {
func.func @test() -> tensor<20x180xi64> {
%c = stablehlo.constant dense<20176> : tensor<20x180xi64>
%0 = stablehlo.iota dim = 1 : tensor<20x180xi64>
%1 = stablehlo.multiply %0, %c : …
```
> resolve #491: Iota Rewrite

- src/enzyme_ad/jax/Passes/CanonicalizeFor.cpp
- src/enzyme_ad/jax/Passes/LibDeviceFuncsRaisingPass.cpp
- src/enzyme_ad/jax/Passes/SelectPatterns.cpp
- src/enzyme_ad/jax/Passes/SelectPatterns.h
- test/lit_tests/canonicalizefor/selectExtractToExtractSelect.mlir
- test/lit_tests/raising/libdevice_remove_const.mlir
The absence of these patterns prevents raising for certain constants. They also run later as part of scf.for canonicalization.
> copy select-of-extract patterns to libdevice-raise

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- src/enzyme_ad/jax/TransformOps/TransformOps.td
- src/enzyme_ad/jax/primitives.py
- test/lit_tests/raising/affine_to_stablehlo5.mlir
- test/lit_tests/selectcompiotaconstsimplify.mlir
Refer to [the unit test i wrote](https://github.com/EnzymeAD/Enzyme-JAX/blob/a6d8cf6c7e107f04f9c98e2e41d8e1929c0c6c5c/test/lit_tests/selectcompiotaconstsimplify.mlir) for everything I tested.
I have tested:
- all six flags
- swapping the const and iota
- higher dimensions (but LT only)
- if the constant is negative or above the iota dimension
I have also changed the `affine_to_stablehlo5.mlir unit` test, because it was further reduced by this optimization.
> Add Select-Compare-Iota optimization (#535)

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- test/lit_tests/while-transpose-test.mlir
Transform this:
out = while(in)
{
y = something(in)
....
x =tr(a)  //inner transpose
return x
}
c = tr(out) //outer transpose
to this:
z = tr(in) //Moved to before while
out = while(z)
{
new = tr(z) //Another moved to beginning of while
y=something(new)
...
return a
}
c = out;
> Moving transpose to before whileOp  + broadcast iota error fix

- src/enzyme_ad/jax/Implementations/StableHLOAutoDiffOpInterfaceImpl.cpp
- test/lit_tests/diffrules/stablehlo/broadcastindim.mlir
Should ideally fix the bug in EnzymeAD/Reactant.jl#1117
> Fix reverse mode derivative for `stablehlo.broadcast_in_dim`

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- src/enzyme_ad/jax/TransformOps/TransformOps.td
- test/lit_tests/sliceextend.mlir
fixes https://github.com/EnzymeAD/Enzyme-JAX/issues/713
```mlir
// RUN: enzymexlamlir-opt --enzyme-hlo-generate-td="patterns=slice_extend" --transform-interpreter --enzyme-hlo-remove-transform %s | FileCheck %s
func.func @extend_operations(%arg28: tensor<1x24x96xf64>, %5290: tensor<1x8x80xf64>) -> (tensor<1x10x80xf64>, tensor<1x10x8xf64>, tensor<1x10x8xf64>) {
%11825 = stablehlo.slice %5290 [0:1, 0:8, 72:80] : (tensor<1x8x80xf64>) -> tensor<1x8x8xf64>
%11826 = stablehlo.slice %5290 [0:1, 0:8, 0:8] : (tensor<1x8x80xf64>) -> tensor<1x8x8xf64>
%11827 = stablehlo.slice %arg28 [0:1, 17:24, 8:88] : (tensor<1x24x96xf64>) -> tensor<1x7x80xf64>
%11828 = "enzymexla.extend"(%5290) <{dimension = 1 : i64, lhs = 1 : i64, rhs = 1 : i64}> : (tensor<1x8x80xf64>) -> tensor<1x10x80xf64>
%11829 = …
```
> Extend of slice becomes slice of extend

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- src/enzyme_ad/jax/TransformOps/TransformOps.td
- test/lit_tests/sliceextend.mlir
matches `slice(extend(base))` and now collects all uses of the base operand that are either:
* the same extendop as the one previously matched
* a slice op that doesn't alter the extended dimension, followed by the same extendop.
And creates a single extendop at the top.
from:
```mlir
func.func @extend_operations(%arg0: tensor<1x24x96xf64>, %arg1: tensor<1x8x80xf64>) -> (tensor<1x10x80xf64>, tensor<1x10x8xf64>, tensor<1x10x8xf64>) {
%0 = stablehlo.slice %arg1 [0:1, 0:8, 72:80] : (tensor<1x8x80xf64>) -> tensor<1x8x8xf64>
%1 = stablehlo.slice %arg1 [0:1, 0:8, 0:8] : (tensor<1x8x80xf64>) -> tensor<1x8x8xf64>
%2 = stablehlo.slice %arg0 [0:1, 17:24, 8:88] : (tensor<1x24x96xf64>) -> tensor<1x7x80xf64>
%3 = "enzymexla.extend"(%arg1) <{dimension = 1 : i64, lhs = 1 : i64, rhs = 1 : i64}> : …
```
> Finish up extend of slice becomes slice of extend

- src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp
- src/enzyme_ad/jax/TransformOps/TransformOps.td
- test/lit_tests/slicerotate.mlir
- test/lit_tests/slicerotate2.mlir
- test/lit_tests/slicewrap2.mlir
One part of #700
```mlir
func.func @rotate_operations(%arg0: tensor<1x10x80xf64>, %arg1: tensor<1x10x8xf64>, %arg2: tensor<1x10x8xf64>) -> (tensor<1x10x8xf64>, tensor<1x10x7xf64>) {
%0 = stablehlo.slice %arg0 [0:1, 0:10, 0:8] : (tensor<1x10x80xf64>) -> tensor<1x10x8xf64>
%1 = stablehlo.slice %arg0 [0:1, 0:10, 1:8] : (tensor<1x10x80xf64>) -> tensor<1x10x7xf64>
%3 = "enzymexla.rotate"(%0) <{amount = 3 : si32, dimension = 1 : si32}> : (tensor<1x10x8xf64>) -> tensor<1x10x8xf64>
%4 = "enzymexla.rotate"(%1) <{amount = 3 : si32, dimension = 1 : si32}> : (tensor<1x10x7xf64>) -> tensor<1x10x7xf64>
return %3, %4 : tensor<1x10x8xf64>, tensor<1x10x7xf64>
}
// CHECK:      func.func @rotate_operations(%arg0: tensor<1x10x80xf64>, %arg1: tensor<1x10x8xf64>, %arg2: tensor<1x10x8xf64>) -> …
```
> rotations of slices of base into slice of single rotation

- src/enzyme_ad/jax/Implementations/StableHLOAutoDiffOpInterfaceImpl.cpp
- test/lit_tests/diffrules/stablehlo/while6.mlir
Checking for ConstOp would not work in while6 because it was a pop.
> do not cache known iter count for whileop

- src/enzyme_ad/jax/Dialect/EnzymeXLAOps.td
- src/enzyme_ad/jax/Passes/LowerEnzymeXLALinalg.cpp
- test/lit_tests/linalg/qr.mlir
@avik-pal the StableHLO code after the `jit_call` in the `enzymexla.linalg.lu` code I guess is for reconstructing the L and U matrices from the output of the LAPACK routine right?
Also, in the case of the QR, it needs some workspace memory for storing intermediate computations. @wsmoses should we leave the allocation to XLA / EnzymeXLA or should we allocate it ourselves in the wrapper? I feel like reusing the workspace buffer across multiple LAPACK calls would be something that could be optimized in the future, but don't know how to properly express it.
I might also need to call another LAPACK function, `*ORGQR`/`*UNGQR`, to retrieve the Q matrix.
> Add `linalg.qr` op

- src/enzyme_ad/jax/Passes/LLVMToAffineAccess.cpp
- test/lit_tests/gpualloc_deadstore_nonasync.mlir
This fixes a crash where `gpu.alloc` does not return an async token
> Explicit check for gpu.alloc async token

- src/enzyme_ad/jax/Dialect/Ops.cpp
- test/lit_tests/canonicalize-pointer2memref.mlir
Turning `memref.load(pointer2memref(gep(gep(...(x)...))))` into `memref.load(pointer2memref(x))`
> Canonicalize memref.load(pointer2memref(gep))

- src/enzyme_ad/jax/Passes/ConvertPolygeistToLLVM.cpp
We used to be bitcating pointers because of typed pointers, which are now gone, but we are getting address space mismatches. Repurpose bitcast insertion for address casts. Not sure this is the right approach or whether we should change the function signature to accept pointers in another address spaces.
> use addrspacecast insteadof bitcast for pointers

- .github/workflows/pr-jax-main.yml
I think it's useful to be able to quickly check the diff of JAX, in case we need to check what changed during an update.  Here's an example of how it looks like: https://github.com/giordano/Enzyme-JAX/pull/2.
> [CI] Include JAX diff in commit message

- .github/workflows/pr-jax-main.yml
The test is a bit crude, but based on testing I've done so far (see for example [this run](https://github.com/EnzymeAD/Enzyme-JAX/actions/runs/17887012407/job/50862029822) where the open PR step was skipped, because we currently have other commits in #1400), it seems to be working well: if there are commits we don't expect on the target branch, don't open (well, overwrite) the PR.
> [CI] Don't open PR for updating JAX if there are already other commits on the branch

- src/enzyme_ad/jax/clang_compile.cc
The overloads for many of the TargetRegistry functions using string triples are deprecated and will be removed soon. Migrate Enzyme off them to prevent breakage.
> Remove call to deprecated createTargetMachine overload
